# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCharacteristics',
            fields=[
                ('brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=50)),
                ('max_carrying_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentActiveMachines',
            fields=[
                ('machine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('current_carrying_load', models.IntegerField(default=0)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrackingApp.BrandCharacteristics')),
            ],
        ),
    ]
