# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentactivemachines',
            old_name='brand_id',
            new_name='brand_name',
        ),
    ]
