# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackingApp', '0004_auto_20161125_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentactivemachines',
            name='overload_value',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
