# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackingApp', '0005_currentactivemachines_overload_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentactivemachines',
            name='overload_value',
        ),
    ]
