# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackingApp', '0007_auto_20161129_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcharacteristics',
            name='brand_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
